### ISSUE TITLE
Give users the right to make their own root name and password

### ISSUE THREAD

**Issue by Ekultek** [PandaLinux/base-64#4]
You should give users the right to make their own username and password during installation instead of making 'root' the default, this will also increase security and will make it more 'user friendly' I can start working on this tomorrow

**Comment by abhi1693** [comment]
The default `root` username and password is set using [shadow package](https://github.com/PandaLinux/base-64/blob/master/build-system/shadow/build.sh). You can create a new user and set the password here by passing the credentials. Or, you can implement your own method if it is easy and user friendly for the end-user.

Send me `PR` when you are done. I'm looking forward to it!

**Comment by Ekultek** [comment]
I can add a prompt in there, idk if I'm going to be able to test it though

**Comment by abhi1693** [comment]
I've been thinking about this and I think that adding a custom user at this point is of no use. First, I would like to complete a basic system, more like a skeleton. After this is completed, then we should think of making this user friendly. Right now my goal  is to prepare an `iso` image of the system which we can later use to make more comprehensive system. And that system will be used by the end user. So, adding a custom username and password at this stage if of less importance.

I have opened a [gitter chat](https://gitter.im/PandaLinux/base-64), and we should discuss all these matters over there.

**Comment by Ekultek** [comment]
Use slack, I can't access gitter

**Comment by abhi1693** [comment]
May I know the reason why you can't access it?

**Comment by abhi1693** [comment]
I've also created the [slack account](https://panda-linux.slack.com/messages)

**Comment by Ekultek** [comment]
I don't have access due to my job
- Thomas Perkins
